name: FTP Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Variables públicas a nivel de workflow
env:
  FTP_HOST: web0151.zxcs.nl
  FTP_USERNAME: u127684p143111
  FTP_DESTINATION: /domains/missstarinternational.com/public_html

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: web0151.zxcs.nl
        username: u127684p143111
        password: ${{ secrets.VIMEXX_FTP_PASSWORD }}
        server-dir: /domains/missstarinternational.com/public_html/
        dangerous-clean-slate: true
