name: Deploy to FTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Variables públicas a nivel de workflow
env:
  FTP_HOST: web0151.zxcs.nl
  FTP_USERNAME: u127684p143111
  FTP_DESTINATION: /domains/missstarinternational.com/public_html

jobs:
  deploy:
    name: 📂 Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history

      - name: 📂 Sync files via FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ env.FTP_HOST }}
          user: ${{ env.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "."
          remoteDir: ${{ env.FTP_DESTINATION }}
          options: "--delete --asci -v --exclude-glob .git* --exclude-glob .github/* --exclude-glob scripts/* --exclude-glob node_modules/* --exclude-glob *.md --exclude-glob *.json --exclude-glob *.bat --exclude-glob *.log --exclude-glob temp*"
