name: FTP Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Variables públicas a nivel de workflow
env:
  FTP_HOST: web0151.zxcs.nl
  FTP_USERNAME: u127684p143111
  FTP_DESTINATION: /domains/missstarinternational.com/public_html

jobs:
  deploy:
    name: 📂 Deploy Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: web0151.zxcs.nl
          username: u127684p143111
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/missstarinternational.com/public_html/
